import type { Product, Sale, OperationalSummaryItem, Customer } from './types';

export const salesData: Sale[] = [
  { name: 'Jan', total: Math.floor(Math.random() * 5000) + 1000 },
  { name: 'Fev', total: Math.floor(Math.random() * 5000) + 1000 },
  { name: 'Mar', total: Math.floor(Math.random() * 5000) + 1000 },
  { name: 'Abr', total: Math.floor(Math.random() * 5000) + 1000 },
  { name: 'Mai', total: Math.floor(Math.random() * 5000) + 1000 },
  { name: 'Jun', total: Math.floor(Math.random() * 5000) + 1000 },
  { name: 'Jul', total: Math.floor(Math.random() * 5000) + 1000 },
  { name: 'Ago', total: Math.floor(Math.random() * 5000) + 1000 },
  { name: 'Set', total: Math.floor(Math.random() * 5000) + 1000 },
  { name: 'Out', total: Math.floor(Math.random() * 5000) + 1000 },
  { name: 'Nov', total: Math.floor(Math.random() * 5000) + 1000 },
  { name: 'Dez', total: Math.floor(Math.random() * 5000) + 1000 },
];

export const operationalSummaryData: OperationalSummaryItem[] = [
    { id: '1', customer: 'Padaria Pão Quente', description: 'Pagamento de Fatura #1023', type: 'Recebimento', amount: '+ R$ 1.200,00' },
    { id: '2', customer: 'Mercado Central', description: 'Venda de 100 pães franceses', type: 'Venda', amount: '+ R$ 85,00' },
    { id: '3', customer: 'Fornecedor Farinita', description: 'Pagamento de NF #589', type: 'Pagamento', amount: '- R$ 2.500,00' },
    { id: '4', customer: 'Supermercado Bom Preço', description: 'Venda de 50 pães de queijo', type: 'Venda', amount: '+ R$ 75,00' },
];

export const products: Product[] = [
  { id: '1', name: 'Pão Francês', stock: 250, imageUrl: 'https://placehold.co/600x400.png', 'data-ai-hint': 'french bread' },
  { id: '2', name: 'Pão de Queijo', stock: 150, imageUrl: 'https://placehold.co/600x400.png', 'data-ai-hint': 'cheese bread' },
  { id: '3', name: 'Croissant', stock: 80, imageUrl: 'https://placehold.co/600x400.png', 'data-ai-hint': 'croissant pastry' },
  { id: '4', name: 'Bolo de Chocolate', stock: 15, imageUrl: 'https://placehold.co/600x400.png', 'data-ai-hint': 'chocolate cake' },
  { id: '5', name: 'Sonho de Creme', stock: 45, imageUrl: 'https://placehold.co/600x400.png', 'data-ai-hint': 'cream pastry' },
  { id: '6', name: 'Baguete', stock: 60, imageUrl: 'https://placehold.co/600x400.png', 'data-ai-hint': 'baguette bread' },
];

export const customers: Customer[] = [
    { 
        id: 'CUST-001', 
        name: 'Padaria Central', 
        email: 'contato@padariacentral.com.br', 
        phone: '(11) 3456-7890', 
        status: 'ativo', 
        registeredAt: '2023-03-14',
        type: 'pessoa-juridica',
        doc: '12.345.678/0001-90',
        address: 'Rua das Flores, 123 - Centro',
        totalPurchasesValue: 15420.50,
        totalOrders: 89,
        exchanges: 3,
        lastPurchaseDate: '13/01/2024',
        pendingAmount: 245.00,
        purchaseHistory: [
            { id: 'P001', date: '2024-05-01', product: 'Pão Francês', quantity: 200, totalValue: 180.00 },
            { id: 'P002', date: '2024-05-08', product: 'Pão de Queijo', quantity: 150, totalValue: 225.00 },
        ],
        exchangeHistory: [],
        financialHistory: [],
    },
    { 
        id: 'CUST-002', 
        name: 'Mercado São João', 
        email: 'compras@mercadosaojoao.com.br', 
        phone: '(11) 2345-6789', 
        status: 'ativo', 
        registeredAt: '2022-11-19',
        type: 'pessoa-juridica',
        doc: '98.765.432/0001-10',
        address: 'Av. São João, 456 - Vila Nova',
        totalPurchasesValue: 28750.80,
        totalOrders: 156,
        exchanges: 1,
        lastPurchaseDate: '14/01/2024',
        pendingAmount: 0,
        purchaseHistory: [
            { id: 'P004', date: '2024-05-03', product: 'Baguete', quantity: 50, totalValue: 250.00 },
        ],
        exchangeHistory: [],
        financialHistory: [],
    },
     { 
        id: 'CUST-003', 
        name: 'Café da Esquina', 
        email: 'pedidos@cafedaesquina.com.br', 
        phone: '(21) 98765-4321', 
        status: 'inativo', 
        registeredAt: '2023-01-10',
        type: 'pessoa-juridica',
        doc: '11.222.333/0001-44',
        address: 'Rua do Comércio, 789 - Centro',
        totalPurchasesValue: 5300.00,
        totalOrders: 42,
        exchanges: 0,
        lastPurchaseDate: '10/12/2023',
        pendingAmount: 0,
        purchaseHistory: [],
        exchangeHistory: [],
        financialHistory: [],
    },
    { 
        id: 'CUST-004', 
        name: 'Maria Silva', 
        email: 'maria.silva@email.com', 
        phone: '(31) 91234-5678', 
        status: 'ativo', 
        registeredAt: '2024-02-28',
        type: 'pessoa-fisica',
        doc: '123.456.789-00',
        address: 'Av. Principal, 1500 - Bairro Sul',
        totalPurchasesValue: 850.75,
        totalOrders: 15,
        exchanges: 2,
        lastPurchaseDate: '18/05/2024',
        pendingAmount: 75.00,
        purchaseHistory: [],
        exchangeHistory: [],
        financialHistory: [],
    },
];
